- service/chrome/.gitattributes
- service/chrome/HeadlessChrome-66.0.3343.0.tar.gz
> Fix chrome

- .circleci/config.yml
- client/Makefile
- client/package.json
- client/scripts/version.sh
- client/yarn.lock
adds circleci build. Builds on normal branch. Then deploys/git releases on master branch merge.
> added circle-ci file

- .gitignore
- example/repo/Jenkinsfile
- example/repo/Makefile
- example/repo/README.md
- example/repo/bootstrap.sh
- example/repo/sanities/google-fail-example.test.js
- example/repo/sanities/google-load-example.test.js
- example/repo/sanities/google-search.test.js
> Example repo

- client/package.json
- client/src/cli.js
- client/src/run-tests.js
- client/src/utils.js
- client/yarn.lock
This PR resolves https://github.com/tophat/sanity-runner/issues/4. This change formats console logs in a similar style to Jest.
Preview:
> Format console log using styling similar to Jest

- website/siteConfig.js
See DNS change on https://github.com/js-org/js.org/pull/2541
> docs: switch to sanity-runner.js.org

- client/scripts/version.sh
> Fix version script

- .circleci/config.yml
- service/Makefile
> install-ci -> install

- service/Makefile
- service/serverless.yml
reduce everything to 1 S3 bucket with sub directories. makes complexity alot nicer. 1 lambda fucntion + 1 s3.
> move to one s3 bucket for simplicity

- .all-contributorsrc
> docs: add all-contributorsrc

- Dockerfile
- service/serverless.yml
adds IAM for accessing secrets
> adds ARN for accessing secrets

- client/src/cli.js
- client/src/run-tests.js
- client/yarn.lock
- service/package.json
- service/serverless.yml
- service/src/lambdaHandler.js
- service/src/testRunner.js
- service/yarn.lock
will retry up to 3 times when an error is thrown. this should stop random lambda crashes for occuring. 
if a test fails it will throw an error and retry, but on last retry attempt will return normally
> retry 3 times if failure

- service/src/testRunner.js
> feat: retry on failure

- .github/README.md
> chore: deploy new version

- .github/README.md
> feat: deploy new version

- .circleci/config.yml
- .github/README.md
- .releaserc.js
- Makefile
- client/Dockerfile
- client/Makefile
- client/README.md
- client/config.json
- package.json
publish docker image on release 
Also Added some better documentation
> feat: Add docker publish

- .circleci/config.yml
> fix: docker publish

- service/serverless.yml
Fix: copy paste error on ARN for pinpoint
> fix: ARN for pinpoint is wrong

- service/package.json
- service/src/alertOnResult.js
- service/src/secrets.js
- service/src/testRunner.js
- service/yarn.lock
closes #122 
Adds support for alerting to slack. 
requires `ALERT=true` to be set as a variables. This allows the user the option to turn off notification/not send to slack if they testing a local branch.
requires `sanity_runner/slack_api_token` to exist within aws secretmanager
Picks up Slack channel + test description via pragams in top level comment of a test. 
EX.
```
/** 
* @Owner Fake Team Name
* @Slack #itsachannelname
* @Description 
*  - test
**/
import { setDefaultOptions } from 'expect-puppeteer'
const constants = require('../constants/constants');
describe('Baseline', async () => {
setDefaultOptions({ timeout: 6000 })
test('Tophat responds successfully', async () => {
await expect("asdasdas").toEqual("123123")
},900000)
})
``` 
the above test will result in an alert like the …
> Adds slack notifcation

- service/src/alertOnResult.js
updates slack message so image in thread + ENV in top level message.
> updates how slack message looks

- service/serverless.yml
allow ability to set custom s3 bucketname via env like all other properties
> feat: custom s3 bucketname

- .github/README.md
- service/README.md
adds docs about env variables used for our serverless template
fixes: #145
> docs: add docs on env variables for serverless

- service/src/testRunner.js
Nice to log the results from failed run. Currently only see logs related to the last failed. Good to know why unstable tests are failing even if they eventually pass
> feat: log the results from failed retries,.

- service/README.md
- service/serverless.env
- service/src/alertOnResult.js
Adds Slack handler option. Can prepend an @here or @group to slack messages
also sneaking in another serverless.env ENV for local deploying.
> Adds handler

- .github/README.md
- client/src/run-tests.js
`lambda.invoke` returns a promise, and failed in next line as JSON.parse trys to parse something that doesnt exist.
```
SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse (<anonymous>)
at testResultPromise (/snapshot/client/src/run-tests.js:0:0)
at process._tickCallback (internal/process/next_tick.js:68:7)
at Function.Module.runMain (pkg/prelude/bootstrap.js:1308:13)
at startup (internal/bootstrap/node.js:274:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
Caught rejection
SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse (<anonymous>)
at testResultPromise (/snapshot/client/src/run-tests.js:0:0)
at process._tickCallback (internal/process/next_tick.js:68:7)
at Function.Module.runMain (pkg/prelude/bootstrap.js:1308:13)
at startup …
```
> fix: Invoke returns promise 

- client/src/run-tests.js
> fix: keepalive in lambda https agent

- service/terraform/main.tf
Adds prefix to IAM role so its accuratly described.
Also adds VPC-policy based on if VPC input variables are set
> fix: add missing terraform

- service/package.json
- service/src/alerts/index.ts
- service/src/alerts/pagerDuty.ts
- service/src/alerts/slack.ts
- service/src/alerts/utils.ts
- service/src/jestConfig/e2eFrameworkSetup.ts
- service/src/logger.ts
- service/src/testRunner.ts
- yarn.lock
Add https://github.com/winstonjs/winston logging which takes care of the JSON formatting for us. It's always quite configurable.
> feat: improve console logging

- packages/client/src/backends/lambda.ts
- packages/client/src/backends/local.ts
- packages/client/src/index.ts
- packages/service/src/core/index.ts
- packages/service/src/core/testHooks/globalSetup.ts
- packages/service/src/core/testHooks/setupFilesAfterEnv.ts
- packages/service/src/core/testRunner.ts
- packages/types/src/index.ts
NOTE: Default viewport is now correctly set to 1920x1080.
> feat: add default viewport options
