service/src/jestSetup/screenshotReporter.js
If we use `skip` in the test files, the test runner will throw error. This is because we are assuming screenshots always exist if a test does not pass, so it tries to find screenshot in the skipped test too.
=> Fix skipping tests break in the test runner

client/src/utils.js
related to issue #50 
because its running in async, the dictionary it returns is a promise. Doesnt need to be ran in async, and this will allow passing in vars via --var to work again :)
=> doesnt need to be async

client/src/cli.js
QA:
```
./bin/sanity-runner-macos  --test-dir ~/repos/thm-sanity/dist/ --include presentation.test.js
```
should ONLY run the presentation.test.js
```
./bin/sanity-runner-macos  --test-dir ~/repos/thm-sanity/dist/ --exclude presentation.test.js
```
should run all BUT presentation.test.js 
```
~/repos/sanity-runner/client/bin/sanity-runner-macos --config config.json
```
```
{
"testDir": "./dist",
"outputDir": "./output",
"var": {
"APP_ENV": "CA"
},
"lambdaFunction": "sanity-runner-dev-default",
"exclude": "presentation.test.js"
}
```
should run all BUT presentation.test.js 
```
{
"testDir": "./dist",
"outputDir": "./output",
"var": {
"APP_ENV": "CA"
},
"lambdaFunction": "sanity-runner-dev-default",
"include": "presentation.test.js"
}
```
should ONLY run the presentation.test.js
=> adds exclude flag + renames test-path-pattern to include

client/src/utils.js
The print message incorrectly show `passed` for failed test counts. Fix the typo in the code.
=> fix: incorrect printed message for failed test count.

service/package.json, service/yarn.lock
Reverts tophat/sanity-runner#79
Puppeteer may need to be left alone over Chromium version concerns. Reverting this update just in case, knowing that GreenKeeper will reopen a PR for the update later.
=> chore: revert "Update puppeteer in group default to the latest version 🚀"

.github/README.md
Links to client usages was broken. Update the link.
=> docs: Fix link on README.md

service/src/run.js, service/src/testRunner.js
the console.logs doesnt have all relevant information that can be used for tracking. Here i am generating my own json object (jest --json json blob isnt proper) and adding some extra key/values.
Added:
- retry count
- test_variables 
- duration of test. 
- sets status as skipped when test is skipped
=> Log relevant test info

service/Makefile, service/serverless.yml
dynamic service name will stop conflicting cloudformation names in same ENV, also just echo out function name
=> dynamic service name and echo out funciton name

service/src/alertOnResult.js, service/src/run.js
increases timeout on presigned URL to 2 hours
and adds message with screenshot to object in s3.
ex)
=> Update screenshot times

.github/README.md, service/Makefile, service/serverless.env, service/serverless.yml
adds ability to optionally set lambda in a VPC. needed to do the stuff with `SERVERLESS_VPC_ENABLED` as a work around to conditionally set vpc config (as maybe you dont always want it). this also ensures serverless never crashes, and at most will ever only throw a warning that self:custom.vpc:false doesnt exist, in which case will just not put lambda in a vpc. 
--force needed to be added to serverless deploy because if a lambda already exists without VPC setting, it wont update the lambda and silently do nothing. force will update the existing lambda to be configured with VPC only with --force
added a seperate issue to doc ENVs https://github.com/tophat/sanity-runner/issues/145 will do so in another pr
=> allow optional lambda in VPC

client/README.md, service/README.md, service/package.json, service/src/alertOnResult.js
Adds Pagerduty alerting support.
- added a `constructMessage` function that returns a dict with all needed text for any given alert. This makes it simpler to add new alerts in the future. 
- adds pagerduty alert. configured by env PAGERDUTY_ALERT = true . 
Pagerduty service is configured via metadata similiar to slack channel. Due to integration keys being a little more secure however, the metadatra must point to the name of a secret in AWS secret manager. 
ex) created secret will have name `sanity_runner/pagerduty-tophat` with key/value  `integration_key` : `<some integration key value>`
and then the metadata must have `@pdIntegrationId pagerduty-tophat` to send alerts to said pagerduty integration 
```
/**
* @Owner Tophat
* @Pagerduty pagerduty-tophat
* @Description 
*  - confirms …
```
=> Add pagerduty support

service/Makefile, service/src/alertOnResult.js
adds testname as dedup key to prevent alerts on every test failure 
fixes #155
=> Pg add dedup

service/src/alertOnResult.js, service/src/jestSetup/e2eFrameworkSetup.js, service/src/lambdaHandler.js, service/src/run.js, service/src/testRunner.js
add custom user agent to browser. 
Because the lambda is starting another jest process, it must pass the context in via jestConfig()  
tested and confirm it gets set in our datadog apm traces 
https://app.datadoghq.com/logs?cols=host%2Cservice%2C%40lambda.request_id&event&from_ts=1589912013672&index=&live=true&messageDisplay=inline&query=%40request.headers.user-agent%3A%22TophatSanityRunner%2Fundefined%22&stream_sort=desc&to_ts=1589915613672 
can see here 
ALSO: snuck in logging errorMessages from tests. we currently dont see this in lambda logs, and would be usefull
=> feat: add custom user agent

service/src/alertOnResult.js
Sends resolve event to PG on tests configured with PG whenever they pass.
This adds one API call everytime these tests are ran, which shouldnt be an issue. 1 event every 10 min shouldnt be throttled. Can add checking if event is triggered/awknowledged first before sending resolve event if we want. 
This will auto resolve a PG alarm if it was previously failing then started working again
=> Resolve pagerduty

service/src/alertOnResult.js
Adds run book pragma that lets you link a Runbook URL that gets added to an alert. 
ex)
```
* @Owner Experience: Assessment
* @Slack #bot-proving-ground
* @Runbook https://tophat.atlassian.net/wiki/spaces/TOP/pages/885358599/Sanity+Slack+Failure+-+Runbook
```
=> feat: Add Runbook pragma

service/src/alertOnResult.js
Previously, when Pagerduty alerting was enabled (i.e. when `PAGERDUTY_ALERT` test variable was set) but a test didn't have `Pagerduty` set in metadata, the sanity runner would throw an error. This should not be an error condition.
This branch has been deployed to the following lambda: `sanity-runner-no-error-on-m-asiaqefsjrmxuhciil4c`.
You can test these changes by running a failing test using the lambda, with the `PAGERDUTY_ALERT` test variable set:
1. Force a sanity test to fail by adding `return Promise.reject()` to the end of the test.
2. Make the following change to the sanities config file:
```
diff --git a/config.json b/config.json
index aece119..3682751 100644
--- a/config.json
+++ b/config.json
@@ -2,8 +2,9 @@
"testDir": "./dist",
"outputDir": "./output",
"var": {
-    "APP_ENV": …
```
=> fix: avoid throwing an error on missing Pagerduty integration

.github/actions/docker-push/actions.yml, .github/workflows/cicd.yml, .gitignore, .releaserc.js, client/Makefile, client/src/cli.js, service/Dockerfile, service/Makefile, service/package.json, service/src/jestSetup/e2eFrameworkSetup.js
- Create a new Dockerfile for running the service in AWS Lambda container. The image will be published to Docker Hub and make it easy to extend.
- The major `version` of service will now match `puppeteer-core`. This is to make it clearer which puppeteer (and chrome) version that the sanity runner container is supporting.
=> feat: add docker container image for aws lambda container support

service/src/alerts/index.ts, service/src/alerts/slack.ts, service/src/alerts/utils.ts, service/src/testRunner.ts, service/src/types.ts
https://tophat.atlassian.net/jira/software/c/projects/WEB/boards/247?modal=detail&selectedIssue=SERVINFRA-1209
=> feat: add runId to slack thread when sanities fail

Dockerfile, service/service.Dockerfile
Node 16 support released! https://aws.amazon.com/about-aws/whats-new/2022/05/aws-lambda-adds-support-node-js-16/
=> feat: update service docker image to node 16

client/package.json, service/package.json, service/src/jestConfig/puppeteerEnvironment.ts, service/src/jestConfig/puppeteerSetup.ts, yarn.lock
BREAKING CHANGE: See puppeteer changelog for entries from v10 to v14. This also updates the version of chromium used to 102.0.5002.0 (r991974).
=> feat: upgrade puppeteer from v10 to v14

terraform/main.tf
The s3 bucket is meant to store transient objects so it's safe to force destroy when the terraform stack is being cleaned up.
=> feat: allow force deletion of screenshot s3 bucket
